### ISSUE TITLE
ERROR: cannot find the connection layer fn

### ISSUE THREAD

**Issue by mikeqzy** [g-fiche/Mesh-VQ-VAE#1]
Hi, thank you for your great work! However, when I'm trying to train the mesh-vq-vae following README, I get this error message in the terminal: `ERROR: cannot find the connection layer fn`
I found that in the default config `config_autoencoder/config_medium`, in `modelconv.connection_layer_lst` there's `pool0-6, unpool0-6`, while in the download link [here](https://github.com/papagina/MeshConvolution/tree/master/train/0223_GraphAE27_compare/connections/dfaust), only `pool0-3, unpool0-3` is provided. Could you please check the exact mesh convolutional network config you use in the experiment? Thanks!

**Comment by g-fiche** [comment]
Hello,
Thanks a lot for your interest in our work!
There is an error in the link: [here](https://github.com/papagina/MeshConvolution/tree/master/train/0223_GraphAE27_compare/connections/dfaust2) is the right data to download for the connections. I will update the README accordingly; thank you for noticing this!
