### ISSUE TITLE
train on AMASS dataset

### ISSUE THREAD

**Issue by zhanganny** [g-fiche/Mesh-VQ-VAE#2]
Hello! Thanks for your great work! It's confusing that in your paper the Mesh-VQ-VAE is trained on AMASS dataset. But the implement in this repository is trained on BEDLAM.
Could you please release the version trained on AMASS dataset（the pre-trained weights and the code for AMASS dataset as described in the paper）? 
Thank you so much! Looking forward to your reply.

**Comment by g-fiche** [comment]
Hello,

The weights provided are the ones used in all experiments. 

The motions used in BEDLAM are sampled from the AMASS dataset but are augmented with more diverse body shapes (please refer to the [BEDLAM](https://bedlam.is.tue.mpg.de/index.html)) paper and supplementary materials for more information. 

We originally trained Mesh-VQ-VAE on the AMASS dataset but then noticed that training on the animations from BEDLAM was slightly faster and achieved the same performance.

If you wish to train Mesh-VQ-VAE on AMASS, you can replace the path of the training data in the config file with the path of the previously downloaded AMASS dataset, and it will work the same way.

**Comment by zhanganny** [comment]
> The weights provided are the ones used in all experiments.

OK, I get it~
